### ISSUE TITLE
Tornar FieldInvalidError serializavel como json

### ISSUE THREAD

**Issue by mayconfrr** [scjorge/pydantic_br#1]
Ao tentar utilizar o FieldInvalidError como parte de um modelo e utilizar o método model_dump_json(), uma exceção é lançada

Meu caso de uso usando Powertools for AWS Lambda
```python
@app.exception_handler(RequestValidationError)
def handle_validation_error(e: RequestValidationError) -> Response[Problem]:
    return Response(
        status_code=HTTPStatus.BAD_REQUEST,
        content_type="application/problem+json",
        body=Problem.of(
            HTTPStatus.BAD_REQUEST,
            errors=e.errors(),
        ).model_dump_json(exclude_none=True),
    )
```
Exceção lançada:
```
"Unable to serialize unknown type: <class 'pydantic_br.field_erros.FieldInvalidError'>",
```

**Comment by scjorge** [comment]
Eu lancei uma nova versão v1.0.1 alterando as exceptions para o uso das exceptions nativas do pydantic.

pydantic v1 > pydantic.PydanticTypeError
pydantic v2 > pydantic_core.PydanticCustomError

Realize um teste com a versão nova e me informa se foi solucionado.

**Comment by mayconfrr** [comment]
Deu certo, muito obrigado
